#

server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    #  Compression 
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
    gzip_min_length 256;

    #  Assets statiques 
    location ~* \.(js|css|png|jpg|jpeg|webp|svg|ico|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    #  Pages HTML 
    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-cache";
    }

    #  Health check interne 
    location /health {
        return 200 '{"status":"ok","service":"frontend"}';
        add_header Content-Type application/json;
    }
}